# Generated by Django 3.1 on 2020-08-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagrebte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mytype',
            field=models.CharField(blank=True, choices=[('تجربة', 'تجربة'), (' استفسار', ' استفسار')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_type', to='tagrebte.posttype'),
        ),
    ]
