# Generated by Django 3.1 on 2020-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagrebte', '0002_auto_20200822_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mytype',
            field=models.CharField(blank=True, choices=[('تجربة', 'تجربة'), ('استفسار', 'استفسار')], max_length=15, null=True),
        ),
    ]
